
story:
  Hero: 
    Persona: Coder
    Activity: Developing
    Subject: SaaS
  Problem:
    Villain: 
    Internal: Need to Develop a SaaS Product
    External: Unsure of the best SaaS Tech Stack
    Philosophical: Code vs No Code
  Guide: 
    Name: SaaS.Dev
    Empathy: 
    Authority: 
  Plan: 
    Offer: Headless SaaS Platform
    Process: 
    Agreement:
  Action: 
    Direct:
    Transitional:
      - Build: Get Started for Free
      - Launch: Iterate Quickly with user feedback
      - Grow: Scale with your customers
  Failure: 
    - Lifetime of regrets
  Transformation:
    From: 
    To: 
  Success: 
    - Launch a successful product


- The Header (very few words to explain your offer)
- The Stakes (what are you saving customers from)
- The Value Prop (what are the benefits to the customer)
- The Guide (introduce your brand who can solve your problem)
- The Plan (the path to do business with us and solve your problem)
- The Explanatory Paragraph (the long-form story brand)
- The Price Choices (Your list of products/offers)
